services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\CurrencyManageBundle\Command\:
    resource: '../../Command/'
  Tourze\CurrencyManageBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CurrencyManageBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  Tourze\CurrencyManageBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CurrencyManageBundle\Service\:
    resource: '../../Service/'
