services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\CurrencyManageBundle\Command\:
    resource: '../../Command/'
  Tourze\CurrencyManageBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CurrencyManageBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CurrencyManageBundle\Service\:
    resource: '../../Service/'
  
  # 确保测试时可以访问 AdminMenu 服务
  Tourze\CurrencyManageBundle\Service\AdminMenu:
    public: true
