services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  # Only DataFixtures services are allowed in services_test.yaml
  Tourze\CurrencyManageBundle\DataFixtures\:
    resource: '../../DataFixtures/'
    
  Tourze\CurrencyManageBundle\Tests\Fixtures\:
    resource: '../../../tests/Fixtures/'